### Add user1
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@mail.com",
  "password": "password"
}

### Add user2
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@mail.com",
  "password": "password"
}

### Login user1
### Replace env variable in http-client.env.json with response
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

### Login user2
### Replace env variable in http-client.env.json with response
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "user2",
  "password": "password"
}

### Add group1
POST http://localhost:8080/api/groups
Authorization: {{user1_token}}
Content-Type: application/json

{
  "groupName": "group1"
}

### Add first post
POST http://localhost:8080/api/posts/?groupId=1
Authorization: {{user1_token}}
Content-Type: application/json

{
  "post": "This is the first post",
  "category" : "First",
  "location": { "type": "Point", "coordinates": [65,80] }
}

### Add first comment
POST http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}
Content-Type: application/json

{
  "commentText": "This is the first comment"
}

### Add second comment
### EXPECTED: Error
POST http://localhost:8080/api/posts/1/comment
Authorization: {{user2_token}}
Content-Type: application/json

{
"commentText": "This is the second comment"
}

### Add second comment
POST http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}
Content-Type: application/json

{
  "commentText": "This is the second comment"
}

### Get comments for post
### EXPECTED: 2 comments
GET http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}

### Update comment with wrong User
### EXPECTED: ERROR
PUT http://localhost:8080/api/posts/comment/1
Authorization: {{user2_token}}
Content-Type: application/json

{
  "updatedText": "This is not the updated first comment"
}

### Update comment
PUT http://localhost:8080/api/posts/comment/1
Authorization: {{user1_token}}
Content-Type: application/json

{
  "updatedText": "This is the updated first comment"
}

### Get comments
### EXPECTED: 2 comments, first is updated
GET http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}

### Delete comment
### EXPECTED: Error
DELETE http://localhost:8080/api/posts/comment/2
Authorization: {{user2_token}}

### Get comments
### EXPECTED: 2 comments
GET http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}

### Delete comment
DELETE http://localhost:8080/api/posts/comment/2
Authorization: {{user1_token}}

### Get comments
### EXPECTED: 1 comment
GET http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}