### Add group1
POST http://localhost:8080/api/groups?userId=1
Authorization: {{user1_token}}
Content-Type: application/json

{
  "groupName": "group1"
}

### Add group2
POST http://localhost:8080/api/groups?userId=2
Authorization: {{user2_token}}
Content-Type: application/json

{
  "groupName": "group2"
}

### Add user1 to group2
POST http://localhost:8080/api/members?groupId=2
Authorization: {{user1_token}}
Content-Type: application/json

{
  "adminRights": "false"
}

### Add first post
POST http://localhost:8080/api/posts/?groupId=1
Authorization: {{user1_token}}
Content-Type: application/json

{
  "post": "This is the first post",
  "category" : "First",
  "location": { "type": "Point", "coordinates": [65,80] }
}

### Add second post
POST http://localhost:8080/api/posts/?groupId=2
Authorization: {{user1_token}}
Content-Type: application/json

{
  "post": "This is the second post",
  "category" : "Second",
  "location": { "type": "Point", "coordinates": [64,80] }
}

### Add third post
POST http://localhost:8080/api/posts/?groupId=2
Authorization: {{user2_token}}
Content-Type: application/json

{
  "post": "This is the third post",
  "category" : "First",
  "location": { "type": "Point", "coordinates": [65,81] }
}

### Add first comment
POST http://localhost:8080/api/posts/1/comment
Authorization: {{user1_token}}
Content-Type: application/json

{
  "commentText": "This is the first comment"
}

### Get all posts from user1
### EXPECTED: 2
GET http://localhost:8080/api/posts/byUser?userId=1
Authorization: {{user1_token}}

### Get all posts from user2 & group1
### EXPECTED: 2
GET http://localhost:8080/api/posts/byUserOrGroup?userId=2&groupId=1
Authorization: {{user1_token}}

### Get all posts after timestamp
### EXPECTED: 3
GET http://localhost:8080/api/posts/byTime
Authorization: {{user1_token}}
Content-Type: application/json

{"time": "2021-06-05T07:26:59.529","operation": "greater"}

### Get all posts around location
### EXPECTED: 1
GET http://localhost:8080/api/posts/byLocation
Authorization: {{user2_token}}
Content-Type: application/json

{"longitude":"65","latitude": "80","radius": "1"}

### Add Site
POST http://localhost:8080/api/site/
Authorization: {{user1_token}}
Content-Type: application/json

{
  "siteName": "Site1",
  "location": { "type": "Point", "coordinates": [65,80] }
}

### Get all posts around site
### EXPECTED: 1
GET http://localhost:8080/api/posts/bySite
Authorization: {{user2_token}}
Content-Type: application/json

{"sitename":"Site1","radius": "1"}


### Update post 1 with user2
### EXPECTED: ERROR
PUT http://localhost:8080/api/posts/1
Authorization: {{user2_token}}
Content-Type: application/json

{"text":"Unauthorized Update from User 2"}

### Update post 1 with user1
PUT http://localhost:8080/api/posts/1
Authorization: {{user1_token}}
Content-Type: application/json

{"text":"This is the updated post from User 1"}

### Delete post 1 with user2
### EXPECTED: ERROR
DELETE http://localhost:8080/api/posts/1
Authorization: {{user2_token}}

### Delete post 2 with user1
DELETE http://localhost:8080/api/posts/2
Authorization: {{user1_token}}

### Get updated post
### EXPECTED: 1 Posts with one updated text
GET http://localhost:8080/api/posts/byUser?userId=1
Authorization: {{user2_token}}

