### Add user1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@mail.com",
  "password": "password"
}

### Add group1
POST http://localhost:8080/api/groups?userId=1
Content-Type: application/json

{
  "groupName": "group1"
}

### Add group2
POST http://localhost:8080/api/groups?userId=1
Content-Type: application/json

{
  "groupName": "group2"
}

### Add first post
POST http://localhost:8080/api/posts/?userId=1&groupId=1
Content-Type: application/json

{
  "post": "This is the first post",
  "category" : "First",
  "location": { "type": "Point", "coordinates": [65,80] }
}

### Add second post
POST http://localhost:8080/api/posts/?userId=1&groupId=2
Content-Type: application/json

{
  "post": "This is the second post",
  "category" : "Second",
  "location": { "type": "Point", "coordinates": [64,80] }
}

### Add third post
POST http://localhost:8080/api/posts/?userId=1&groupId=1
Content-Type: application/json

{
  "post": "This is the third post",
  "category" : "First",
  "location": { "type": "Point", "coordinates": [65,81] }
}

### Add first comment
POST http://localhost:8080/api/posts/1/comment
Content-Type: application/json

{
  "commentText": "This is the first comment",
  "userId" : "1"
}

### Get Posts of user1
### ECPECTED: 3 Posts
GET http://localhost:8080/api/posts/byUser?userId=1

### Get Posts of user2
### ECPECTED: 0 Posts
GET http://localhost:8080/api/posts/byUser?userId=2

### Get Posts of Group2
### ECPECTED: 1 Post
GET http://localhost:8080/api/posts/byUserOrGroup?groupId=2

### Update post2
PUT http://localhost:8080/api/posts/2
Content-Type: application/json

{
"text" : "This is the updated second post"
}

### Get Posts after Time
### ECPECTED: 3 Posts
GET http://localhost:8080/api/posts/byTime
Content-Type: application/json

{
  "time": "2021-06-05T07:26:59.529+00:00",
  "operation": "greater"
}

### Get Posts before Time
### ECPECTED: 0 Posts
GET http://localhost:8080/api/posts/byTime
Content-Type: application/json

{
  "time": "2021-06-05T07:26:59.529+00:00",
  "operation": "less"
}

### Add Site
POST http://localhost:8080/api/site/
Content-Type: application/json

{
  "siteName": "Site1",
  "location": { "type": "Point", "coordinates": [65,80] }
}

### Get Post from Site within Radius
### ECPECTED: 1 Posts
GET http://localhost:8080/api/posts/bySite
Content-Type: application/json

{
  "sitename": "Site1",
  "radius": "1000000"
}

### Get Posts from Long,Lat Lpcation within Radius
### ECPECTED: 1 Posts
GET http://localhost:8080/api/posts/byLocation
Content-Type: application/json

{
  "longitude": "65",
  "latitude": "80",
  "radius": "1"
}

### Delete second Post
DELETE http://localhost:8080/api/posts/2

### Get Posts
### ECPECTED: 2 Posts, no second post
GET http://localhost:8080/api/posts/byUserOrGroup?groupId=2

### Delete User
DELETE http://localhost:8080/api/users/1

### Get Posts after Time
### ECPECTED: 0 Posts
GET http://localhost:8080/api/posts/byTime
Content-Type: application/json

{
  "time": "2021-06-05T07:26:59.529+00:00",
  "operation": "greater"
}